version: "2"
services:
  mysql:
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/docker/server/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql:5.7
  redis:
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/docker/server/redis:/data
      - /etc/localtime:/etc/localtime:ro
    image: redis:3.2
  php72:
    container_name: "php72"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /usr/local/docker/server/www:/var/www/html
      - /usr/local/docker/server/php:/usr/local/etc/php
      - /etc/localtime:/etc/localtime:ro
    links:
      - "mysql"
      - "redis"
    image: php:7.2-fpm
  nginx:
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "php72"
    volumes:
      - /usr/local/docker/server/www:/usr/share/nginx/html
      - /usr/local/docker/server/nginx:/etc/nginx
      - /usr/local/docker/server/logs/nginx.logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    image: nginx:latest
